try {
    hello()
} catch (error) {
    console.log(error)
}

//another
try {
    anotherFn()
} catch (error) {
    console.log('Esto es un error')
}

